kadas-albireo/kadas-albireo2

cmake/FindQGIS.cmake

Address typos, allow building with QGIS in a special prefix

---

.github/workflows/windows.yml

this will cancel running jobs on the branch or in pull request when there is a new push

add concurrency to windows builds

---

kadas/gui/mapitems/kadasmapitem.cpp

Some map items property set methods can modify the state, so clone it at last

Preserve Image Item scale on clone

---

kadas/gui/kadasmapcanvasitem.cpp

If the map canvas item has an invalid position or bounding box, be quiet about it

Catch reprojection errors for map canvas items

---

kadas/gui/mapitemeditors/kadasgpxrouteeditor.cpp
kadas/gui/mapitemeditors/kadasgpxwaypointeditor.cpp
kadas/gui/mapitemeditors/kadasmapitemeditor.cpp
kadas/gui/mapitemeditors/kadasmapitemeditor.h
kadas/gui/mapitemeditors/kadasredliningitemeditor.cpp
kadas/gui/mapitemeditors/kadasredliningtexteditor.cpp
kadas/gui/mapitemeditors/kadassymbolattributeseditor.cpp
kadas/gui/maptools/kadasmaptoolcreateitem.cpp
kadas/gui/maptools/kadasmaptoolmeasure.cpp

The rich text editor for pins is usable again.
The previous approach to register editors was depending on specific behavior of some compilers and not compatible with MSVC.
See https://stackoverflow.com/questions/3104923/static-initialization

Properly initialize registry

---

kadas/app/ui/kadaswindowbase.ui
kadas/resources/stylesheet.css

Remove transparency for layer browser menu
Left old - right new

Browser menu remove transparency and bigger buttons

---

kadas/app/kadasmainwindow.cpp

Fixes a crash when loading an invalid layer
Followup https://github.com/kadas-albireo/kadas-albireo2/pull/118
CC @domi4484

Add nullptr guard

---

kadas/app/3d/kadas3dmapcanvaswidget.cpp
kadas/app/3d/kadas3dmapcanvaswidget.h

The helper is parented to the widget, so it will be cleaned by Qt, if we also have the `std::unique_ptr` delete it, it will crash.

Fix crash on exit

---

vcpkg/ports/py-kadas-requirements/requirements.txt

Refs https://jira.swisstopo.ch/browse/MGDIGRE_SB-1155

Install pip-system-certs instead of python-certifi-win32

---

kadas/gui/mapitemeditors/kadasmapitemeditor.cpp

This was missing from https://github.com/kadas-albireo/kadas-albireo2/commit/c3ec157f80fc4ef4cf74ad834b0f561dd15abdd8

fix missing redlining editor

---

kadas/app/CMakeLists.txt
kadas/app/kadas.env.in
kadas/app/kadaspythonintegration.cpp
kadas/app/main.cpp

Adds a new file kadas.env, this file is read on kadas start and configures environment variables.
These are used to configure PYTHONPATH and QGIS_PREFIX_PATH. These are only added to the build directory and help to find packges from vcpkg (or possibly other install trees).
This helps to start debugging in visual studio without any manual interaction.

Preconfigure paths for debug sessions

---

kadas/app/mapswipe/kadasmapswipecanvasitem.cpp
kadas/app/mapswipe/kadasmapswipecanvasitem.h

Render in background and make use of rendercache of alrady rendered mapcanvas image
The `waitForFinished` call was blocking the main thread until we'd have a fully rendered image, which could take a long time, especially with remote layers.

Fix mapswipe tool

---

vcpkg/ports/qgis/fix3dnavigation.patch
vcpkg/ports/qgis/portfile.cmake

Fixes the calculation of the ground point (Z=0) at a given screen position also when the camera is tilted.
This massively improves the navigation usability.
There is still room for improvement. We now take the Z=0 point, but it would be even better to take a terrain point.

Fix tilted 3D screen to world coord

---

kadas/app/kadasmainwindow.cpp
kadas/gui/catalog/kadasarcgisportalcatalogprovider.cpp
kadas/gui/catalog/kadasvbscatalogprovider.cpp
kadas/gui/kadascatalogbrowser.h

It works for geocatalogs of type `arcgisportal`.
I could not test it with geocatalogs of type `vbs`. In the default settings_full.ini there is no such catalog configured.
I added a settings `portal/load-arcgis-layer-as-vector` if someone need to work with the layers as raster. Or to quickly switch back in case of issues.

Use vector variant for arcgis layers

---

kadas/app/kadasapplication.cpp
kadas/app/kadasmainwindow.cpp
kadas/gui/catalog/kadasarcgisportalcatalogprovider.cpp
kadas/gui/catalog/kadasvbscatalogprovider.cpp
kadas/gui/kadascatalogbrowser.h

- Use "type" to differentiate arcgis Raster/Vector layers and use "arcgismapserver"/"arcgisfeatureserver" accordingly
- Remove related settings as no longer needed
- Fix first layer insertion point for groups
- Fix sublayer index in groups (for arcgisfeatureserver)
- Fix Layer infos not working for feature layers: EbenenInformationen: Keine Informationen für diese Ebene verfügbar

Differentiate arcgis Vector/Raster layers

---

vcpkg/ports/qgis/3dfrustumfix.patch
vcpkg/ports/qgis/portfile.cmake

Fixes a problem with frustum terrain (z=0 plane) intersection, where if the camera is too close to the origin we get into a floating point calculation precision problem.
An alternative approach would be #315 which completely disables origin shift. This seems to work nicely as well, but the origin shift functionality promises better results for large scenes (>50km) which we want to be able to handle.

Fix the 3d frustum calculation when close to origin

---

kadas/app/3d/kadas3dintegration.cpp
kadas/app/3d/kadas3dlayertreemodel.cpp
kadas/app/3d/kadas3dlayertreemodel.h
kadas/app/3d/kadas3dmapcanvaswidget.cpp

For 3D canvas, this PR fixes:
- dialog title: "Kadas 3D"
- initial visibility of layer tree view accoring to setting
- behavior of the layer tree: the check state in the legend was incorrect. The original implementation was similar to the snapping in QGIS with partially checked nodes but it was buggy and I am not sure that partially checked nodes are correctly rendered. I went for a simpler approach where only layer nodes are checkable.

3D: fix layer tree sync + dialog title + layer tree view state

---

kadas/gui/mapitems/kadasrectangleitembase.cpp
kadas/gui/mapitems/kadasrectangleitembase.h

we make the frame visible by default for new objects, but opening older projects with former text should stay without frames

fix opening text with no frames

---

kadas/app/mapgrid/kadasmapgridlayerrenderer.cpp
kadas/app/mapgrid/kadasmapgridlayerrenderer.h
kadas/core/kadaslatlontoutm.cpp
kadas/core/kadaslatlontoutm.h
python/kadascore/auto_generated/kadaslatlontoutm.sip.in

More generic (higher) labels have priority
Build a list of drawn label rectangles to check for intersections
Now
Previous
Now
Previous

Don't superpose labels

---

vcpkg/ports/qgis/3dchunkloaderconcurrency.patch
vcpkg/ports/qgis/portfile.cmake

This fixes a problem where the rendering results for some chunks (tiles) are not taken into account.
Longer explanation:
`loadTexture()` is called from the constructor of `FlatTerrainChunkLoader`, which is called from `QgsFlatTerrainGenerator::createChunkLoader` (same for DEM, not only Flat). In `QgsChunkedEntity::startJob`, a connection is made to `QgsChunkLoader::finished` which is emited eventually through `onImageReady()` if that texture is loaded very quickly, this is emitted _before_ the connection is made and therefore the job is never finished.
Even worse: we have a maximum of 4 jobs, so if they are all occupied by stalled jobs, no more jobs are done at all.
By using a QueuedConnection, we make sure that the `onImageReady` signal (and the subsequent `finished` signal will be …

Fix 3D chunks are rendered too quickly

---

kadas/app/kadascanvascontextmenu.cpp
kadas/core/kadascoordinateformat.cpp
kadas/core/kadascoordinateformat.h
python/kadascore/auto_generated/kadascoordinateformat.sip.in
vcpkg/ports/qgis/flagDegreesUseUntranslatedStringSuffix.patch
vcpkg/ports/qgis/portfile.cmake

When using the right click menu "Copy coordinates" in the map canvas

Don't translate direction suffix 'N', 'E', 'S', 'W'

---

kadas/gui/mapitemeditors/kadasredliningtexteditor.cpp

Font: Arial 12
Color: black
Border color: white
Fix https://jira.swisstopo.ch/browse/MGDIGRE_SB-1308
Fix a bug introduced in #346 that caused `syncItemToWidget` to be called many times

Default text for text item
