kadas-albireo/kadas-albireo2

- com.sourcepole.kadas.appdata.xml
Makes sure the warnings from appstream-glib pass
> Polish appstream metadata

- kadas/gui/mapitems/kadaspictureitem.cpp
Use corner point for quadrant calculation (instead of image center)
Old:
New:
> Fix glitches at image corner

- vcpkg/ports/qgis/portfile.cmake
- vcpkg/ports/qgis/wcsLayerName.patch
See https://github.com/qgis/QGIS/pull/57493
> Use title for WCS layer name

- kadas/analysis/kadasviewshedfilter.cpp
Otherwise some parts are not computed
> Use max of width/height to compute viewshed

- kadas/app/CMakeLists.txt
- kadas/app/kadasapplication.cpp
- kadas/app/main.cpp
> fix loading of translations

- kadas/gui/mapitems/kadasgeometryitem.cpp
This was happening when brush style is set to something different than solid.
Note: this is a workaround. Proper solution would be to use proper QGIS Symbology rendering instead of QPainter primitives
> Fix transparency wrongly added to outline for transparent brushes

- vcpkg/ports/py-kadas-requirements/requirements.txt
Added markupsafe lib which is needed by the routing plugin.
> Update py requirements.txt

- kadas/gui/mapitems/kadascircleitem.cpp
- kadas/gui/mapitems/kadascircularsectoritem.cpp
- kadas/gui/mapitems/kadascoordinatecrossitem.cpp
- kadas/gui/mapitems/kadasgpxrouteitem.cpp
- kadas/gui/mapitems/kadasgpxwaypointitem.cpp
- kadas/gui/mapitems/kadaslineitem.cpp
- kadas/gui/mapitems/kadasmapitem.cpp
- kadas/gui/mapitems/kadasmapitem.h
- kadas/gui/mapitems/kadaspictureitem.cpp
- kadas/gui/mapitems/kadaspointitem.cpp
- kadas/gui/mapitems/kadaspolygonitem.cpp
- kadas/gui/mapitems/kadasrectangleitem.cpp
- kadas/gui/mapitems/kadasselectionrectitem.cpp
- kadas/gui/mapitems/kadassymbolitem.cpp
- kadas/gui/mapitems/kadastextitem.cpp
- kadas/gui/milx/kadasmilxitem.cpp
Properly initialize item registry along the lines of https://github.com/kadas-albireo/kadas-albireo2/pull/107
> Fix item position

- cmake/SIPMacros.cmake
> Add definition protected=public for bindings

- vcpkg/ports/py-kadas-requirements/requirements.txt
```
ImportError: cannot import name 'formatargspec' from 'inspect'
```
> Fix python error

- kadas/app/kadasapplayerhandling.cpp
not yet sure why, but the layer is not correctly showing up in Kadas
> [mvt] update data sources

- kadas/gui/mapitems/kadaspictureitem.cpp
- kadas/gui/mapitems/kadaspictureitem.h
- kadas/gui/mapitems/kadasrectangleitembase.cpp
- kadas/gui/mapitems/kadasrectangleitembase.h
- python/kadasgui/auto_generated/mapitems/kadaspictureitem.sip.in
- python/kadasgui/auto_generated/mapitems/kadasrectangleitembase.sip.in
- python/kadasgui/kadasgui_auto.sip
This is a preliminary work to add text + rectangle items.
> create QgsRectangleItemBase as base of QgsPictureItem

- kadas/gui/kadasitemlayer.cpp
see https://github.com/qgis/QGIS/pull/33827/files?w=1
> const fixes + deprecation

- kadas/app/mapgrid/kadasmapgridlayerrenderer.cpp
- kadas/app/mapgrid/kadasmapgridlayerrenderer.h
- kadas/core/kadaslatlontoutm.cpp
- kadas/core/kadaslatlontoutm.h
- python/kadascore/auto_additions/kadaslatlontoutm.py
- python/kadascore/auto_generated/kadaslatlontoutm.sip.in
> Improve MGRS grid 

- kadas/gui/search/kadasworldlocationsearchprovider.cpp
use a blockingGet
partial fix for MGDIGRE_SB-1169
> fix world locator search

- CMakeLists.txt
Will reset them to 0.0.0 when the workflow part is implemented
> Add CACHE for version variables to be able to use them in the workflow

- kadas/gui/search/kadaslocationsearchprovider.cpp
- kadas/gui/search/kadasworldlocationsearchprovider.cpp
fix crash in remote search (missing break)
consider possible different CRS of map canvas and main annotation layer
> more fixes to search

- vcpkg/ports/qgis/portfile.cmake
- vcpkg/ports/qgis/wcs-additional-HTTP-headers.patch
See https://github.com/qgis/QGIS/pull/59635
> Set additional HTTP headers for WCS provider

- kadas/app/mapswipe/kadasmapswipecanvasitem.cpp
- kadas/app/mapswipe/kadasmapswipecanvasitem.h
- kadas/app/mapswipe/kadasmapswipetool.cpp
waiting for feedback in MGDIGRE_SB-974
> [swipe tool] increase line width and change cursor when hovering the line

- kadas/app/3d/kadas3dlayertreemodel.cpp
- kadas/app/3d/kadas3dlayertreemodel.h
- kadas/app/3d/kadas3dmapcanvaswidget.cpp
- kadas/app/3d/kadas3dmapcanvaswidget.h
- kadas/app/CMakeLists.txt
https://github.com/user-attachments/assets/604cd92a-af8d-497e-845c-66bf5eed91af
> add layer tree for 3D canvas

- kadas/app/3d/kadas3dmapcanvaswidget.cpp
- kadas/app/3d/kadas3dmapcanvaswidget.h
actually correctly saving dock + position would deserve a bit of love in QGIS base class to handle settings.
> add 3d canvas as an integrated dock

- kadas/app/kadasmainwindow.cpp
use QgsBlockingNetworkRequest + fix special chars in path
> Support insert image from a URL with query

- kadas/app/kadasapplication.cpp
Port from https://github.com/kadas-albireo/kadas-albireo/blob/da8849d71988ca6595e3a655e8393c9fa37b15d5/src/app/main.cpp#L658-L665
> Port --clearsettings

- kadas/app/kadasmainwindow.cpp
- vcpkg/ports/qgis/locator-bold-pr60689.patch
- vcpkg/ports/qgis/portfile.cmake
see https://github.com/qgis/QGIS/pull/60689
and widget height:
> better visibility of groups in locator

- kadas/gui/search/kadaslocationsearchprovider.cpp
- kadas/gui/search/kadaslocationsearchprovider.h
- kadas/gui/search/kadasworldlocationsearchprovider.cpp
> improve polygon visibility in searches

- kadas/app/kadasmainwindow.cpp
- kadas/gui/search/kadaslocaldatasearchprovider.cpp
* fix extent intersection if crs is different
* use display expression rather than feature id
* fix search in non-spatial layers
> fix local search

- kadas/app/kadaspluginmanager.cpp
- kadas/app/ui/kadaspluginmanager.ui
> larger size for plugin manager

- kadas/app/kadaspluginmanager.cpp
- kadas/app/kadaspluginmanager.h
* adjust columns to content
* use the checkbox for clicking
> improve plugin manager

- share/python/plugins/kadas_gpkg/kadas_gpkg_export.py
- share/python/plugins/kadas_gpkg/kadas_gpkg_layer_list.py
And support arcgisfeatureserver layers
> Fix gpkg export rewrite (for some gpkgs)

- kadas/gui/kadasitemlayer.cpp
- kadas/gui/kadasitemlayer.h
- kadas/gui/mapitems/kadasmapitem.cpp
- kadas/gui/mapitems/kadasmapitem.h
- python/kadasgui/auto_additions/kadasitemlayer.py
- python/kadasgui/auto_additions/kadaslocationsearchprovider.py
- python/kadasgui/auto_generated/kadasitemlayer.sip.in
- python/kadasgui/auto_generated/search/kadasalternategotolocatorfilter.sip.in
- share/python/plugins/kadas_gpkg/kadas_gpkg_export.py
This works by:
1. Flagging item to be filtered with a custom property
2. Save the temporary .qgs project
3. Unflag flagged item
4. Remove flagged item from the .xml
> GPKG layer export respect extent for redlining layers

- kadas/resources/stylesheet.css
> Fix stylesheet for QMenu::item

- share/python/plugins/kadas_about/kadas_about_ts.pro
- share/python/plugins/kadas_gpkg/kadas_gpkg_ts.pro
- share/python/plugins/kadas_print/kadas_print_ts.pro
This reverts commit 4836e4ac42e0d709e04848ed65605f702c20d8a7.
> fix translations in plugins

- .github/workflows/build-windows.yml
> Upgrade windows runner

- vcpkg/ports/qgis/62506.patch
- vcpkg/ports/qgis/portfile.cmake
Cleaner alternative for https://github.com/kadas-albireo/kadas-albireo2/pull/300
> Use kadas icon in vector layer properties

- .github/workflows/build-windows.yml
Better abi sha compatibility with kadas-milx
> Pin powershell version

- kadas/gui/search/kadasalternategotolocatorfilter.cpp
This fixes the copy pasting of coordinates with altitude in the search bar
> fix altitude copying in search bar

- kadas/gui/search/kadasalternategotolocatorfilter.cpp
fixes https://jira.swisstopo.ch/browse/MGDIGRE_SB-1070
works for 
40:26:46 N, 079:56:55 W
40:26:46.302 N 079:56:55.903 W
40°26′46″ N 079°56′55″ W
N 40°26′47″ W 079°56′55″
40d 26′ 47″ N 079d 56′ 55″ W
40.4462 N 79.9489 W
40.4462, -79.9489
40° 26.7717 N, 79° 56.93172 W
and more!
> improve search for coordinates

- vcpkg/ports/qgis/mounteverest.patch
- vcpkg/ports/qgis/portfile.cmake
I tried an alternative approach to read the information from the tif, but this was way too slow on load.
> Make 3D mount everest compatible

- kadas/gui/mapitemeditors/kadasredliningtexteditor.cpp
- kadas/gui/mapitemeditors/kadasredliningtexteditor.h
- kadas/gui/mapitems/kadastextitem.h
[Screencast_20250821_160612.webm](https://github.com/user-attachments/assets/2e2fdfee-bdad-4154-8e43-caa6e6b35389)
> Fix jumping text size when changing properties

- kadas/app/3d/kadas3dmapconfigwidget.cpp
Sync 3D config widget with upstream
> Store 3d terrain settings
